name = "worker-workflow-test"

main = "src/index.ts"

compatibility_date = "2024-09-02"

compatibility_flags = []

[observability]
enabled = true

[placement]
mode = "smart"

[[workflows]]
# name of your workflow
name = "workflow-test-1"

# binding name env.MYWORKFLOW
binding = "MY_WORKFLOW"

# this is class that extends the Workflow class in src/index.ts
class_name = "MyWorkflow"

# script_name is required during the beta.
# Must match the "name" of your Worker at the top of wrangler.toml
script_name = "worker-workflow-test"
